- src/ngx-smart-modal/src/components/ngx-smart-modal.component.ts
Remove 'dialog-open' class on dismiss
> Fix issue #31

- package.json
> chore(package): update @types/node to version 8.0.41

- package.json
> chore(package): update @angular/cli to version 1.4.7

- .github/issue_template.md
- README.md
In view of the evolution of the package, I think it would be wise to add an issue template to help the understanding of all.
> Add issue template

- src/ngx-smart-modal/src/components/ngx-smart-modal.component.ts
- src/ngx-smart-modal/tests/components/ngx-smart-modal.component.spec.ts
> Fix visible attribute

- src/app/app.component.scss
- src/app/app.module.ts
- src/app/app.routing.ts
- src/app/autostart/autostart.component.html
- src/app/autostart/autostart.component.spec.ts
- src/app/autostart/autostart.component.ts
- src/app/main/main.component.html
- src/app/main/main.component.ts
- src/ngx-smart-modal/src/components/ngx-smart-modal.component.ts
- src/ngx-smart-modal/src/services/ngx-smart-modal.service.ts
- src/ngx-smart-modal/tests/components/ngx-smart-modal.component.spec.ts
- src/ngx-smart-modal/tests/services/ngx-smart-modal.service.spec.ts
Add autostart mode according to #114, fix AOT build potential error #115 add API method alias and toggle function.
> Bug fixes and improvements

- README.md
- src/app/app.component.scss
- src/app/main/main.component.html
- src/ngx-smart-modal/src/components/ngx-smart-modal.component.ts
- src/ngx-smart-modal/src/ngx-smart-modal.scss
- src/ngx-smart-modal/tests/components/ngx-smart-modal.component.spec.ts
add option to display the modal at the location of the target element,
add custom class to centered vertical,
change DOM modal
> Target Element

- src/app/main/main.component.scss
- src/ngx-smart-modal/package-lock.json
- src/ngx-smart-modal/package.json
- src/ngx-smart-modal/rollup.config.js
- src/ngx-smart-modal/src/components/ngx-smart-modal.component.ts
- src/ngx-smart-modal/src/ngx-smart-modal.scss
- src/ngx-smart-modal/tests/components/ngx-smart-modal.component.spec.ts
Version 7.0.0 changes was throwing rxjs errors on Angular 6.x.x on serve. This rollback fixes any
serve error and removes unecessary perrDependencies
fix #113
> fix: Rollback previous changes and fix peerDependencies

- src/ngx-smart-modal/src/components/ngx-smart-modal.component.ts
Like @khylias figured out the `hasData` function from the ModalComponent works badly.
Unfortunately the function return `false` with some others values than `0`  please see [this fiddle](https://jsfiddle.net/mfua5rqd/1/)
This PR fix the issue
> #127 - Fix hasData return while data is false when casted as a boolean

- src/app/autostart/autostart.component.html
- src/app/bootstrap/bootstrap.component.html
- src/app/feature/feature.component.html
- src/app/foundation/foundation.component.html
- src/app/main/main.component.html
- src/app/materialize/materialize.component.html
> Add HTTPS placeholder image links #145

- README.md
This commit basically adds syntax color to code examples.
> Add some swagg to documentation

- README.md
@Nek- I assigned it to you since you started to format the readme. 😉 
I fixed some code blocks with scss that where colorized as typescript. 😝 
If it's ok for you, you can skip all the running jobs and just merge! 🤘
> Fix some code example types on readme

- README.md
- src/ngx-smart-modal/src/ngx-smart-modal.scss
Fix [#207](https://github.com/biig-io/ngx-smart-modal/issues/207)
> Fix SCSS variable for modal margin, #207

- src/ngx-smart-modal/src/components/ngx-smart-modal.component.ts
> fix(component): Fix event type for triggering dismiss on modals #212

- src/app/_common/header/header.component.html
- src/app/app-routing.module.ts
- src/app/demo/demo.module.ts
Thank you very much @marco10024 for debugging this! 🎉💪
> Fix buggy routing configuration on demo / doc

- src/ngx-smart-modal/package-lock.json
- src/ngx-smart-modal/package.json
- src/ngx-smart-modal/src/components/ngx-smart-modal.component.ts
- src/ngx-smart-modal/src/services/modal-instance.ts
> Fix Uncaught Error #233 by reverting TS version and assignation assertions

- README.md
- src/ngx-smart-modal/package-lock.json
- src/ngx-smart-modal/package.json
- src/ngx-smart-modal/src/components/ngx-smart-modal.component.ts
- src/ngx-smart-modal/src/ngx-smart-modal.scss
> Change close icon from img to svg to support currentColor

- src/app/doc/parts/home/home.component.html
- src/styles.scss
New version of [!242](https://github.com/biig-io/ngx-smart-modal/pull/242)
> Add Browsers support in documentation

- src/app/demo/autostart/autostart.component.html
- src/app/demo/bootstrap/bootstrap.component.html
- src/app/demo/feature/feature.component.html
- src/app/demo/foundation/foundation.component.html
- src/app/demo/main/main.component.html
- src/app/demo/materialize/materialize.component.html
- src/app/doc/parts/options/options.component.ts
- src/ngx-smart-modal/src/components/ngx-smart-modal.component.ts
- src/ngx-smart-modal/src/config/ngx-smart-modal.config.ts
- src/ngx-smart-modal/src/ngx-smart-modal.scss
- src/ngx-smart-modal/src/services/ngx-smart-modal.service.ts
- src/ngx-smart-modal/tests/services/ngx-smart-modal.service.spec.ts
#203 #192
Using WAI-ARIA specification
Trap focus on modal
Checked a11y with ChromeVox, VoiceOver
> Add a11y for modal composant. Add documentation about it

- src/ngx-smart-modal/src/components/ngx-smart-modal.component.ts
- src/ngx-smart-modal/src/services/ngx-smart-modal.service.ts
I have implemented rough solution to load dynamic modals for one of my projects. It should be relatively easy to add support for TemplateRef.
> Rough solution for dynamic components loading

- src/ngx-smart-modal/src/components/ngx-smart-modal.component.ts
> Adds alt text to close icon

- src/ngx-smart-modal/src/components/ngx-smart-modal.component.ts
- src/styles.scss
- fixed a bug of closing the modal window when clicking on the scrollbar
> Scrollbar bugfix
